### ISSUE TITLE
The demo does not seem to work properly

### ISSUE THREAD

**Issue by zqcccc** [valnub/swiper-react-demo#4]
https://codesandbox.io/s/cool-cdn-s2leo?file=/src/App.js

**Comment by ikaracolt** [comment]
I noticed this isn't working also. The thumbnails are not linked to the gallery. I can't figure out what I'm doing wrong. The example code from the tutorial doesn't work.

**Comment by valnub** [comment]
@zqcccc If I download the git repo and follow the instructions (`yarn` and `yarn start`) it works flawlessly for me on Google Chrome and Safari Browser. However, I can confirm that what you posted on codesandbox doesn't work properly, so I assume that there is something different? I think you will have to find out what is different first.

@ikaracolt Can you explain in more detail what is not working exactly?

**Comment by ikaracolt** [comment]
@valnub Samething as in the codesandbox example. The thumbnails don't reference the carousel. If I click on one it doesn't do anything and when i go forward and back in the carousel it doesn't affect the thumbnails.

**Comment by coljung** [comment]
I have a similar issue. I tried watching the video and copy the code from there to my example, and the controller doesnt do anything.

I then copied the App.jsx code into my code, without changing anything, still doesnt work. @valnub 

An update along the way maybe?

Nothing appears broken. so hard to tell what it is :(

I'm going to clone the repo and see if it works in that scenario.

**Comment by coljung** [comment]
@zqcccc Check your Swiper version.

I cloned this repo and noticed the only viable difference was the version, here is 6.0.2, while the latest is 6.4.5

I just replaced it and my code works.

Hope this helps.

P.S. I tested with your code, and indeed if you downgrade the version, it works.

**Comment by valnub** [comment]
Hey everybody, so I had a look at this issue and can confirm what @coljung said.

- The project in this repo uses 6.0.2 which seems to work fine
- Using latest 6.4.5 upgrade of Swiper seems to break functionality

I don't know yet why this is. Will have a look and get back to you guys.

**Comment by valnub** [comment]
Ok, so from what I see I think there is a pretty nasty bug in the latest react-swiper version. Everytime the `onSlideChange` event gets triggered it reports the wrong `activeIndex` value. Instead of a positive value it returns a number <= 0 which is wrong. I'll reach out to the swiperjs team and keep you guys posted on this.

**Comment by valnub** [comment]
Quick update: There seems to be a bug in latest Swiper version. I have reported the issue but the Swiper dev team is currently on vacation. If you encounter the issue you have to either wait for a bugfix or downgrade Swiper version you‘re using. To downgrade follow these steps:

1. Delete node_modules folder
2. Delete yarn.lock file
3. In package.json change swiper version to 6.0.2
4. yarn
5. yarn start

That‘s it. Don’t upgrade until bug is fixed.

**Comment by Dmitriy2020-altair** [comment]
Timo, Hi once again. Unfortunately, even after downgrading to 6.0.2 Thumbs is not working so far. Anyway, thx for your attention.

**Comment by valnub** [comment]
@Dmitriy2020-altair I had a similar issue when downgrading. Turned out I had to completely wipe all .lock files (yarn.lock, package-lock.json) and also completely delete node_modules. Then reinstall all dependencies.

**Comment by coljung** [comment]
I simply did a 'npm uninstall swiper', then ran 'npm install swiper@6.0.2

**Comment by Dmitriy2020-altair** [comment]
Thx brother! Something went wrong, for sure))
I'll try in second...

29 декабря 2020, 18:24:47, от "Pablo Rincon" <notifications@github.com>:


I simply did a 'npm uninstall swiper', then ran 'npm install swiper@6.02

**Comment by Dmitriy2020-altair** [comment]
Timo, thank you! Now it works, v 6.0.2. I did, exactly as you said.
Really appreciate to you. 
Merry Christmas and Happy New Year.))

29 декабря 2020, 12:25:58, от "Timo Ernst" <notifications@github.com>:


@Dmitriy2020-altair I had a similar issue when downgrading. Turned out I had to completely wipe all .lock files (yarn.lock, package-lock.json) and also completely delete node_modules. Then reinstall all dependencies.

**Comment by syssam** [comment]
@valnub any update?

**Comment by valnub** [comment]
@syssam I‘ll have a look this weekend

**Comment by valnub** [comment]
I had a look and the issue still exists in Swiper version 6.4.11.
From what I understand the controller/thumbs feature doesn't sync properly with the main swiper.

So, I opened a new bug ticket here:
https://github.com/nolimits4web/swiper/issues/4206

Let's see what they say.

**Comment by valnub** [comment]
According to the creator of Swiper this is the solution:

Replace this:

```
ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  rootElement
);
```

with this:

```
ReactDOM.render(
  <App />,
  rootElement
);
```

See https://github.com/nolimits4web/swiper/issues/3852#issuecomment-777597779

**Comment by valnub** [comment]
Fixed the issue in https://github.com/valnub/swiper-react-demo/commit/bc5ddb2e34626858bda8a7c00d0d697ad52e6cbb
